=== Robbbo-T/ASI-T2/PRODUCTS/AMPEL360/BWB-Q100/domains/AAA/ata/ATA-57/S1000D/schemas/csdb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.s1000d.org/csdb"
           elementFormDefault="qualified">
  <xs:element name="csdb">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="csdbIdent">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="csdbCode" type="xs:string"/>
              <xs:element name="issueInfo">
                <xs:complexType>
                  <xs:attribute name="issueNumber" type="xs:string" use="required"/>
                  <xs:attribute name="inWork" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="repositories">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="repository" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="type" type="xs:string" use="required"/>
                  <xs:attribute name="path" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Robbbo-T/ASI-T2/PRODUCTS/AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100/domains/AAA/ata/ATA-57/docs/S1000D/metadata/csdb_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<csdb xmlns="http://www.s1000d.org/csdb"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schemas/csdb.xsd">
  <csdbIdent>
    <csdbCode>BWQ1-ATA57-CSDB</csdbCode>
    <issueInfo issueNumber="001" inWork="00"/>
  </csdbIdent>
  <repositories>
    <repository type="data_modules" path="../data_modules/"/>
    <repository type="publication"  path="../publication_modules/"/>
    <repository type="common"       path="../common_information/"/>
    <repository type="multimedia"   path="../multimedia/"/>
    <repository type="indices"      path="../indices/"/>
    <repository type="exchange_in"  path="../exchange/incoming/"/>
    <repository type="exchange_out" path="../exchange/outgoing/"/>
  </repositories>
</csdb>
