=== Robbbo-T/ASI-T2/PRODUCTS/AMPEL360/BWB-Q100/domains/AAA/ata/ATA-57/S1000D/schemas/versioning.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.s1000d.org/csdb/versioning"
           xmlns:tns="http://www.s1000d.org/csdb/versioning"
           elementFormDefault="qualified">
  <xs:element name="versioning">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="git">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="branch">
                <xs:complexType>
                  <xs:attribute name="naming" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="tag">
                <xs:complexType>
                  <xs:attribute name="pattern" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="s1000d">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="issueNumber">
                <xs:complexType>
                  <xs:attribute name="increment" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="inWork">
                <xs:complexType>
                  <xs:attribute name="values" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mapping">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="rule" maxOccurs="unbounded" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Robbbo-T/ASI-T2/PRODUCTS/AMPEL360/AMPEL360_AIR_TRANSPORT/BWB-Q100/domains/AAA/ata/ATA-57/S1000D/metadata/versioning.xml
<?xml version="1.0" encoding="UTF-8"?>
<versioning xmlns="http://www.s1000d.org/csdb/versioning"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="../schemas/versioning.xsd">
  <git>
    <branch naming="copilot/*,feature/*,release/*"/>
    <tag pattern="BWQ1-ATA57-R{major}.{minor}"/>
  </git>
  <s1000d>
    <issueNumber increment="major-change"/>
    <inWork values="01-99 for WIP, 00 for released"/>
  </s1000d>
  <mapping>
    <rule>Release tag MUST include snapshot of indices/ and DMRL</rule>
    <rule>Publication PM and DMRL MUST reference released DMs only</rule>
  </mapping>
</versioning>
